# 编译语言、环境
dist: xenial
os: linux
language: node_js

# Node.js 版本
node_js:
  - 12

cache: npm

# 只有 master 分支更改才触发 CI
branches:
  only:
    - master

before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install # 安装依赖

script:
  - npm run build # 执行打包命令，生成 dist 静态文件

deploy:
  strategy: git
  provider: pages
  skip_cleanup: true      # 跳过清理
  token: $GH_TOKEN        # GitHub Token 变量
  keep_history: true      # 保持推送记录，以增量提交的方式
  local_dir: dist         # 需要推送到 GitHub 的静态文件目录
  target_branch: gh-pages # 推送的目标文件 local_dir -> gh-pages 分支
  on:
    branch: master        # 工作分支
