const PICQH_PREFIX = 'PICQH_';

export const PICQH_CONFIG = PICQH_PREFIX + 'CONFIG'

export const PICQH_UPLOADED = PICQH_PREFIX + 'UPLOADED'

export const PICQH_MANAGEMENT = PICQH_PREFIX + 'MANAGEMENT'
